"use client"

export const dynamic = "force-dynamic"

import { Suspense, useEffect, useState } from "react"
import Link from "next/link"
import { useSearchParams } from "next/navigation"
import { CheckCircle2, Circle, Loader2, Clock, ArrowRight, AlertTriangle } from "lucide-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import type { BookDetails, ChapterStatus } from "@/lib/audiobook-types"

function StatusIcon({ status }: { status: ChapterStatus }) {
  switch (status) {
    case "completed":
      return <CheckCircle2 className="size-4 text-[#4ECDC4]" />
    case "processing":
      return <Loader2 className="size-4 animate-spin text-[#FF6B6B]" />
    case "pending":
      return <Circle className="size-4 text-muted-foreground/40" />
    case "failed":
      return <AlertTriangle className="size-4 text-destructive" />
  }
}

function statusLabel(status: ChapterStatus) {
  switch (status) {
    case "completed":
      return "Completed"
    case "processing":
      return "Processing"
    case "pending":
      return "Pending"
    case "failed":
      return "Failed"
  }
}

function ProcessingPageContent() {
  const searchParams = useSearchParams()
  const bookId = searchParams.get("bookId")
  const [book, setBook] = useState<BookDetails | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!bookId) {
      setLoading(false)
      return
    }

    let mounted = true
    const loadBook = async () => {
      const response = await fetch(`/api/books/${bookId}`, { cache: "no-store" })
      if (!response.ok) return
      const data = (await response.json()) as { book: BookDetails }
      if (mounted) {
        setBook(data.book)
        setLoading(false)
      }
    }

    loadBook()
    const interval = setInterval(loadBook, 2000)
    return () => {
      mounted = false
      clearInterval(interval)
    }
  }, [bookId])

  const chapters = book?.chaptersList ?? []
  const completedCount = chapters.filter((chapter) => chapter.status === "completed").length
  const totalCount = chapters.length
  const isComplete = book?.status === "completed"

  return (
    <div className="mx-auto flex max-w-2xl flex-col gap-6 p-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight text-balance">Generating Audiobook</h1>
        <p className="text-sm text-muted-foreground">
          {book ? `Your audiobook "${book.title}" is being generated by AI.` : "Loading audiobook status..."}
        </p>
      </div>

      <Card className="saas-surface border-white/40">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="text-base">Overall Progress</CardTitle>
              <CardDescription>
                {isComplete
                  ? "All chapters completed!"
                  : `${completedCount} of ${totalCount} chapters completed`}
              </CardDescription>
            </div>
            <span className="text-2xl font-semibold text-[#FF6B6B]">
              {book?.progress ?? 0}%
            </span>
          </div>
        </CardHeader>
        <CardContent>
          <Progress value={book?.progress ?? 0} className="h-2" />
        </CardContent>
      </Card>

      <Card className="saas-surface border-white/40">
        <CardHeader>
          <CardTitle className="text-base">Chapters</CardTitle>
          <CardDescription>Track the progress of each chapter.</CardDescription>
        </CardHeader>
        <CardContent>
          {!bookId ? (
            <p className="text-sm text-muted-foreground">
              No audiobook selected. Go to the dashboard and open progress for a specific book.
            </p>
          ) : loading ? (
            <p className="text-sm text-muted-foreground">Loading chapter progress...</p>
          ) : (
            <div className="flex flex-col divide-y">
            {chapters.map((chapter) => (
              <div
                key={chapter.id}
                className={cn(
                  "flex items-center justify-between py-3",
                  chapter.status === "processing" && "bg-[#FF6B6B]/5 -mx-6 px-6 rounded-md"
                )}
              >
                <div className="flex items-center gap-3">
                  <StatusIcon status={chapter.status} />
                  <span
                    className={cn(
                      "text-sm",
                      chapter.status === "pending" && "text-muted-foreground",
                      chapter.status === "processing" && "font-medium"
                    )}
                  >
                    {chapter.name}
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  {chapter.duration && (
                    <div className="flex items-center gap-1 text-xs text-muted-foreground">
                      <Clock className="size-3" />
                      {chapter.duration}
                    </div>
                  )}
                  <span
                    className={cn(
                      "rounded-sm px-2 py-0.5 text-[10px] font-medium",
                      chapter.status === "completed" && "bg-[#4ECDC4]/10 text-[#4ECDC4]",
                      chapter.status === "processing" && "bg-[#FF6B6B]/10 text-[#FF6B6B]",
                      chapter.status === "pending" && "bg-muted text-muted-foreground",
                      chapter.status === "failed" && "bg-destructive/10 text-destructive"
                    )}
                  >
                    {statusLabel(chapter.status)}
                  </span>
                </div>
              </div>
            ))}
            </div>
          )}
        </CardContent>
      </Card>

      {isComplete && bookId && (
        <div className="flex justify-end">
          <Button asChild>
            <Link href={`/player?bookId=${bookId}`}>
              Listen Now
              <ArrowRight className="size-4" />
            </Link>
          </Button>
        </div>
      )}
    </div>
  )
}

export default function ProcessingPage() {
  return (
    <Suspense fallback={<div className="p-6 text-sm text-muted-foreground">Loading processing status...</div>}>
      <ProcessingPageContent />
    </Suspense>
  )
}
